<?php

namespace AppBundle\Repository;

/**
 * UserKeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserKeyRepository extends \Doctrine\ORM\EntityRepository
{
}
